### ISSUE TITLE
SERVERNAME not resolved in welcome message

### ISSUE THREAD

**Issue by yannickvr** [partiusfabaa/cs2-advertisement#11]
This is the relevant part of my config:

```
  "WelcomeMessage": {
    "MessageType": 0,
    "Message": "Welcome, {BLUE}{PLAYERNAME} to {SERVERNAME}"
  },
  "Ads": [
    {
      "Interval": 60,
      "Messages": [
        {
          "Chat": "Welcome to {SERVERNAME}!"
        }
      ]
    }
  ]
```

When a player joins, they will see `Welcome <whatevertheirplayername is> to {SERVERNAME}`
Every 60 seconds there's a message saying "Welcome to myawesomecs2server". 

Syntax seems the same, so might this be a bug?

**Comment by partiusfabaa** [comment]
Since I made `WecomeMessage` support colors and `{PLAYERNAME}`, other tags are not supported there
