### ISSUE TITLE
[REQ] Translation support improvements

### ISSUE THREAD

**Issue by crashzk** [partiusfabaa/cs2-advertisement#22]
Currently the translation system uses the user's language based on the IP, that is, even if I want to use another language to display the messages I cannot due to my IP.

I believe it would be interesting to add support for translations based on Game/Client and IP. So if I configure the plugin to use the language based on the client/game, if the player chooses the EN language, even without being from a country that speaks EN, he can view the messages in English.

**Comment by partiusfabaa** [comment]
i dont think i can get the clients language

**Comment by crashzk** [comment]
In this case, there would be some way to identify the player's language:

![image](https://github.com/partiusfabaa/cs2-advertisement/assets/32937653/27327984-1348-4870-8a57-7ecfc24b906b)

Or even support to work with this plugin: https://github.com/aprox2/GeoLocationLanguageManagerPlugin

Anyway, in any case we can leave that for the future. It would be interesting to show the message based on the player's game language, since many use a language other than their country's in the game.

**Comment by partiusfabaa** [comment]
yes, as soon as we can get the client language, I'll add that right away

**Comment by crashzk** [comment]
Currently we can use this plugin together: https://github.com/aprox2/GeoLocationLanguageManagerPlugin

Shows the message in the player's language based on his IP location, but if he wants to, he can change the language using the `!lang` command.

> [!WARNING]  
> Only works with ISO codes e.g.: `!lang en` or `!lang lv`
