### ISSUE TITLE
Color not work

### ISSUE THREAD

**Issue by maketou** [partiusfabaa/cs2-advertisement#25]
![image](https://github.com/partiusfabaa/cs2-advertisement/assets/127162439/fada2889-d3bc-4d83-b96d-4d40b1977870)

**Comment by LevGitCode** [comment]
Use the colors of the Counter Strike Sharp API

`namespace CounterStrikeSharp.API.Modules.Utils;

public class ChatColors
{
    public static char Default = '\x01';
    public static char White = '\x01';
    public static char DarkRed = '\x02';
    public static char Green = '\x04';
    public static char LightYellow = '\x09';
    public static char LightBlue = '\x0B';
    public static char Olive = '\x05';
    public static char Lime = '\x06';
    public static char Red = '\x07';
    public static char LightPurple = '\x03';
    public static char Purple = '\x0E';
    public static char Grey = '\x08';
    public static char Yellow = '\x09';
    public static char Gold = '\x10';
    public static char Silver = '\x0A';
    public static char Blue = '\x0B';
    public static char DarkBlue = '\x0C';
    public static char BlueGrey = '\x0A';
    public static char Magenta = '\x0E';
    public static char LightRed = '\x0F';
    public static char Orange = '\x10';

    [Obsolete("Use ChatColors.DarkRed instead.")]
    public static char Darkred = '\x02';`
    
USE:
{Default}
{White}
{DarkRed}
{Green}
{LightYellow}
{LightBlue}
{Olive}
{Lime}
{Red}
{LightPurple}
{Purple}
{Grey}
{Yellow}
{Gold}
{Silver}
{Blue}
{DarkBlue}
{BlueGrey}
{Magenta}
{LightRed}
{Orange}
{Darkred}
