### ISSUE TITLE
Panel ad dindnt show up at the end of a round

### ISSUE THREAD

**Issue by twilightsay** [partiusfabaa/cs2-advertisement#5]
This is my `advertisement.json` content,and panel ads didnt work. The other parts work properly.
```
{
  "Admins": [
    steamid64
  ],
 "Ads": [
    {
      "Interval": 120,			
      "Messages": [
        {
          "Chat": "{RED}text{DEFAULT} text:{RED}{TIME} \n {DEFAULT}text：{RED}{MAP}",
          "Center": "text \n text" 		
        },
        {
          "Chat": "{RED}text{DEFAULT} text:{RED}{TIME}",
          "Center": "text \n text"
        }
      ]
    },
    {
      "Interval": 60,
      "Messages": [
        {
          "Chat": "text"
		
        },
        {
          "Chat": "text"
        }
      ]
    }
  ],
  "Panel":[
	"<font color='#ff00ff'>Game Server</font>",
	"Game Server",
	"TwilightSoul"
	]
}
```
![image](https://github.com/partiusfabaa/cs2-advertisement/assets/16851832/250ff0df-d5a8-4c6f-98f2-70c3777ac81f)

The panel just show the messages form CS2 itself. No any of my messages show up.

**Comment by partiusfabaa** [comment]
Thanks, I'll look into it

**Comment by partiusfabaa** [comment]
[try this](https://github.com/partiusfabaa/cs2-advertisement/releases/tag/v1.0.4)

**Comment by twilightsay** [comment]
> [try this](https://github.com/partiusfabaa/cs2-advertisement/releases/tag/v1.0.4)

Yes it works. Thank u 4 fixin' it.
